name: Check code

# Configures this workflow to run every time a change is pushed
on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  check-code:
    runs-on: ubuntu-latest
    # It is not run if it is a pull_request synchronize event on the main repo
    #if: ${{ ! (github.event_name == 'pull_request' && github.event.action == 'synchronize' && github.event.pull_request.head.repo.full_name == 'marcelropos/HM-DiscordBot')}}
    steps:
      - uses: actions/checkout@v4

      - run: echo ${{github.event.pull_request.head.repo.full_name}}
      #- run: cargo check
      #- run: cargo clippy --all-targets --all-features